### ISSUE TITLE
前端代码编译报错 dva和react 17版本不兼容

### ISSUE THREAD

**Issue by zhu-mingye** [DataLinkDC/dlink#10]
前端代码安装报错 dva和react 17版本不兼容  原因: https://github.com/dvajs/dva/issues/2453
   目前解决方案  降低nodejs版本到14.x 版本及以下  npm版本降低到6.x 版本

**Comment by aiwenmo** [comment]
我的环境参考：npm 7.19.0，node.js 14.17.0，jdk 1.8.0_201，maven 3.6.0，lombok插件 1.18.16。总打包耗时约两分钟
