### ISSUE TITLE
配置本地单机的集群时报错少hadoop 的依赖，请教下，这个在哪里添加，并未在文档找到

### ISSUE THREAD

**Issue by FranklinFair** [DataLinkDC/dlink#107]
![image](https://user-images.githubusercontent.com/57167674/150491688-7deaf0c1-b7d9-449c-ac47-c9121bd858f6.png)

**Comment by aiwenmo** [comment]
请检查plugins下是否有flink对应版本的依赖，如flink-dist等；此外还需要添加hadoop相关依赖如flink-shaded-hadoop-3-uber

**Comment by FranklinFair** [comment]
![image](https://user-images.githubusercontent.com/57167674/151091113-628c288d-6914-4f81-9917-6265bd940718.png)

我是将依赖放到启动脚本里面的

**Comment by aiwenmo** [comment]
解决了吗，没解决的话应该是缺少对应的依赖，可以追踪下Flink源码看看少哪个包
