### ISSUE TITLE
[Bug And Suggests] 

### ISSUE THREAD

**Issue by lovecodec** [DataLinkDC/dlink#11]
too many bugs:
1.can not save sql to job
2.if i use a simple sql based on flink-faker-connector to test sql-graph,the application return nothing;i think sql-graph should not analyse the flink "properties"(connector='faker'.....)。
3.for the column origin,calcite may be a better way,calcite has provided metadata to find the origin of the column
4.cluster manage should consider the free resource of cluster，and show the resource in the ui
5.the project's log is bad,when occur error,i did not see logs

**Comment by aiwenmo** [comment]
1.The draft can't be saved
2.You need to add flink-faker-connector.jar to the lib directory
3.Please wait
4.This will be achieved in the future
5.This problem has been solved in version 0.3.1
Finally, thanks for your suggestions
