### ISSUE TITLE
[Bug] mysql 执行报错

### ISSUE THREAD

**Issue by gaogao110** [DataLinkDC/dlink#116]
<img width="783" alt="1643362839(1)" src="https://user-images.githubusercontent.com/50040900/151523808-10abe743-3476-48b5-9a93-7bfac45d5b39.png">

因为config.getType() 中返回的是“Mysql” 

SQLUtils 中DbType.of(dbType)  只能识别小写的“mysql”

可以用 config.getType().toLowerCase() 规避

**Comment by aiwenmo** [comment]
嗯看下了druid源码，确实是小写，很感谢您的指正，此外，您可以pr到dev分支
