### ISSUE TITLE
多源合并语法执行后，不返回flink Job提交成功的信息。execution of the multi-source merge syntax, the information about the successful submission of flink Job is not returned

### ISSUE THREAD

**Issue by xiebanggui777** [DataLinkDC/dlink#127]
![image](https://user-images.githubusercontent.com/97835322/153367607-ae60694f-ce35-445b-8fe1-ff4455489e5d.png)
提交多源合并的语法，提交Job，可以在yarn-session中看到job，但是dinky中不返回执行成功的信息 BUG。

Submit the syntax of the multisource merge commit Job ，I can see the job in yarn-session ，but the successfully executed information BUG is not returned in dinky.

**Comment by aiwenmo** [comment]
目前先使用 perjob 模式来提交是可以正确返回信息的，remote 的任务一直在同步，目前没找到解决的方式

**Comment by aiwenmo** [comment]
已确认是 Flink 源码 RemoteStreamEnvirment 强制重写了 attached 参数
