### ISSUE TITLE
udf以及connector相关问题

### ISSUE THREAD

**Issue by Samsogo** [DataLinkDC/dlink#156]
udf易用性是否可以优化下呢，如果每次更新或者新增udf都会重启服务而去flink集群的lib下也要新增才可以，使用起来较麻烦，而且如果是多人使用的话，还要考虑多人用的jar包之间是否存在冲突问题

**Comment by Zzm0809** [comment]
pr list:
#1049 
#1090 
#1095 
#1121 
#1138 
#1128 
.....
