### ISSUE TITLE
standalone模式下无法做checkpoint和从指定的checkpoint启动

### ISSUE THREAD

**Issue by zengqinchris** [DataLinkDC/dlink#170]
`
-- 指定对应的checkpoint的路径启动，无法读取，无效
SET execution.checkpoint.path = file:///home/flink-checkpoint/flinkSQL/40d3a742db2c7315b739362bb2d1a8f8/chk-2;

-- SET execution.checkpointing.interval = 30s;
-- SET execution.checkpointing.mode = EXACTLY_ONCE;
-- SET state.checkpoints.num-retained = 3;
-- SET state.backend = filesystem;
-- SET execution.checkpointing.externalized-checkpoint-retention = RETAIN_ON_CANCELLATION;
-- SET state.backend.incremental = true;
-- SET state.checkpoints.dir = file:///home/flink-checkpoint/flinkSQL;
-- SET state.savepoints.dir = file:///home/flink-checkpoint/flinkSQL;
-- SET execution.savepoint.ignore-unclaimed-state = false;

CREATE TABLE log ( 
    database string,  
    table string,  
    type string,  
    ts bigint,  
    xid bigint,  
    data ROW<openid string,unionid string,phone string,create_time string> ,
    rowtime as TO_TIMESTAMP(FROM_UNIXTIME(ts)),
    WATERMARK FOR rowtime AS rowtime - INTERVAL '5' SECOND
) WITH ( 
    'connector.type' = 'kafka', 
    'connector.version' = 'universal', 
    'connector.topic' = 'xxx', 
    'connector.startup-mode' = 'earliest-offset', 
    'connector.properties.group.id' = 'xxx', 
    'connector.properties.bootstrap.servers' = 'xxx', 
    'update-mode' = 'append', 
    'format.type' = 'json', 
    'format.derive-schema' = 'true' 
);

create view myview as select database,type,rowtime,ts,xid,data.openid,data.phone,data.create_time from log 
    where data.openid is not null and data.phone is not null;

create view count_view as 
    select database, DATE_FORMAT(TUMBLE_START(rowtime, INTERVAL '20' SECOND), 'yyyy-MM-dd HH:mm:ss') stt,  
        DATE_FORMAT(TUMBLE_END(rowtime, INTERVAL '20' SECOND), 'yyyy-MM-dd HH:mm:ss') edt,  
        type keyword, 
        count(*) ct, 
        UNIX_TIMESTAMP()*10000 ts 
    from myview
    group by database,type, 
        TUMBLE(rowtime, INTERVAL '20' SECOND);  

-- select * from count_view;

CREATE TABLE sink_count_table ( 
    database varchar(300)  ,
    stt varchar(300)  ,
    edt varchar(300) ,
    keyword varchar(300) ,
    ct bigint,
    ts bigint  
) WITH ( 
    'connector.type' = 'jdbc', 
    'connector.driver' = 'com.mysql.cj.jdbc.Driver', 
    'connector.url' = 'jdbc:mysql://xxx/xxx', 
    'connector.table' = 'xxx', 
    'connector.username' = 'xx', 
    'connector.password' = 'xxx', 
    'connector.write.flush.max-rows' = '5', 
    'connector.write.flush.interval' = '5s' 
);

INSERT INTO sink_count_table
    select database, stt, edt, keyword, ct, ts from count_view;

`

在平台中，开启checkpoint后，无法启动SQL任务
![图片](https://user-images.githubusercontent.com/44901627/157162710-9fc836aa-7305-4d39-8ae1-b49a52bb3ad8.png)

使用配置项可以做checkpoint，但是 通过
SET execution.checkpoint.path = file:///home/flink-checkpoint/flinkSQL/40d3a742db2c7315b739362bb2d1a8f8/chk-2;
来启动无法读取对应的checkpoint，
![图片](https://user-images.githubusercontent.com/44901627/157163168-94ddf129-01e7-4e9d-92dc-5b264ebc5b7f.png)

**Comment by aiwenmo** [comment]
目前 standalone 和 session模式不支持从savepoint或checkpoint启动
