### ISSUE TITLE
hdfs开启ha，命名空间解析异常及临时解决方案

### ISSUE THREAD

**Issue by nvguiyachuang** [DataLinkDC/dlink#174]
dlink版本  0.6.0-SNAPSHOT
flink版本  1.13.5

### 提交任务，yarn-per-job模式，配置hdfs依赖
![8e2652c5dae3862a36f287ec06fa882](https://user-images.githubusercontent.com/44629498/157598820-e6b914c9-0e76-4438-ac7d-4d5174cfd536.png)

### 提交任务，异常信息如下
![9d5037cbb60948c77874461cf2b2f4d](https://user-images.githubusercontent.com/44629498/157599007-33cf07ec-d5c6-47f2-8bad-d24d3046523a.png)

### 解决方案一 
配置命名空间映射，修改/etc/hosts
<img width="378" alt="85cdc25467c7c113a6e46d262829f51" src="https://user-images.githubusercontent.com/44629498/157599357-18ed925c-63ce-49d8-a99f-d8b34964ee24.png">

### 解决方案二
添加HADOOP_HOME环境变量，修改 /etc/profile
export HADOOP_HOME=/opt/cloudera/parcels/CDH/lib/hadoop

### 解决方案三
auto.sh里加一行export HADOOP_HOME=/opt/cloudera/parcels/CDH/lib/hadoop

**Comment by aiwenmo** [comment]
方案可用
