### ISSUE TITLE
Yarn-pre-job不支持配置checkpoint、开启checkpoint间隔、checkpoint超时作废时间、从checkpoint恢复

### ISSUE THREAD

**Issue by lkm0522** [DataLinkDC/dlink#176]
版本：0.5.0
flink版本：1.13.5

- **执行配置：**

![image](https://user-images.githubusercontent.com/72112996/157624403-a0cb4c14-e39f-4b40-bd01-ae8ba5a1bc9f.png)

- **配置超时时间无法生效：**

![image](https://user-images.githubusercontent.com/72112996/157624120-e20c8091-c954-4715-b998-9fddf449be33.png)

- **路径改变不了，无法改变生成checkpoint：**

![image](https://user-images.githubusercontent.com/72112996/157619737-a2ec7cc5-e5af-4013-8f46-c1d79dd6c75f.png)

**Comment by aiwenmo** [comment]
0.5.0是bug版本，可以尝试使用0.5.1或者0.6.0
