### ISSUE TITLE
使用0.5.1 版本运行 Top2 Demo 提示出错

### ISSUE THREAD

**Issue by SIvaCoHan** [DataLinkDC/dlink#193]
1.  Dinky 版本号为 0.5.1
2. Java 版本 OpenJDK8
3. plugins 文件夹
`flink-connector-jdbc_2.12-1.13.3.jar                 
flink-dist_2.11-1.13.3.jar                           
flink-shaded-hadoop-3-uber-3.1.1.7.2.9.0-173-9.0.jar 
flink-table-blink_2.11-1.13.3.jar
flink-csv-1.13.3.jar                                 
flink-json-1.13.3.jar                                
flink-shaded-zookeeper-3.4.14.jar                    
flink-table_2.11-1.13.3.jar`

 
 

[](https://github.com/DataLinkDC/dlink/blob/main/dlink-doc/doc/FlinkAggTable%E5%9C%A8Dlink%E7%9A%84%E5%BA%94%E7%94%A8.md#%E6%91%98%E8%A6%81)Flink AggTable 在 Dlink 的实践

**Comment by aiwenmo** [comment]
出什么错

**Comment by SIvaCoHan** [comment]
0.5.1 版本bug

0.6修改了这个udf的逻辑，0.5.1有从其他任务里编译udf的过程，0.6禁用了
