### ISSUE TITLE
针对per job提交报错的解决

### ISSUE THREAD

**Issue by yangfeishengzhe** [DataLinkDC/dlink#194]
1.在 auto.sh中加入hadoop_home的环境
例如    export HADOOP_HOME="/opt/cloudera/parcels/CDH/lib/hadoop"
2.下载common-cli.jar包到flink/lib/下，同时放到plugins下一份，hdfs/flink/lib/下放一份

**Comment by aiwenmo** [comment]
请描述具体报错
