### ISSUE TITLE
字段血缘中，source2sink在一对多溯源时丢失血缘。

### ISSUE THREAD

**Issue by yanchenyun** [DataLinkDC/dlink#195]
1. 测试用例：
```java
    @Test
    public void test2() {
        String sql = " CREATE TABLE ST ( "
                + "    a STRING, "
                + "    b STRING, "
                + "    c STRING  "
                + ") WITH ( "
                + "    'connector' = 'datagen', "
                + "    'rows-per-second' = '1'  "
                + "); "

                + "CREATE TABLE TT ( "
                + "    A STRING, "
                + "    B STRING  "
                + ") WITH ( "
                + "    'connector' = 'print' "
                + "); "

                + " insert into TT select a||b  A , b||c B from ST ";
        LineageResult result = LineageBuilder.getLineage(sql);
        System.out.println(result);

    }
```

2. 得到结果：
LineageResult(tables=[LineageTable(id=4, name=default_catalog.default_database.ST, columns=[LineageColumn(name=a, title=a), LineageColumn(name=b, title=b), LineageColumn(name=c, title=c)]), LineageTable(id=6, name=default_catalog.default_database.TT, columns=[LineageColumn(name=A, title=A), LineageColumn(name=B, title=B)])], relations=[LineageRelation(id=1, srcTableId=4, tgtTableId=6, srcTableColName=b, tgtTableColName=A), LineageRelation(id=2, srcTableId=4, tgtTableId=6, srcTableColName=c, tgtTableColName=B), LineageRelation(id=3, srcTableId=4, tgtTableId=6, srcTableColName=a, tgtTableColName=A)])

3. 丢失b->B这条血缘。

**Comment by aiwenmo** [comment]
我发现这个问题，晚上会pr个fixbug，初版陆陆续续会有些问题
