### ISSUE TITLE
钉钉告警

### ISSUE THREAD

**Issue by yangfeishengzhe** [DataLinkDC/dlink#201]
配了钉钉告警，任务中使用了，但没有触发
<img width="978" alt="截屏2022-03-18 上午11 06 46" src="https://user-images.githubusercontent.com/33973210/158930008-8e1bf366-cc77-4a58-8c60-e209713a71c2.png">
<img width="700" alt="截屏2022-03-18 上午11 07 43" src="https://user-images.githubusercontent.com/33973210/158930075-9c7311a7-b325-4c55-bd8c-f62f5d182d8d.png">

**Comment by aiwenmo** [comment]
只有上线的作业当完成、失败、停止、未知时才会触发报警
