### ISSUE TITLE
是否有计划增加webHook告警？

### ISSUE THREAD

**Issue by ChangjunZhang** [DataLinkDC/dlink#211]
企业微信群，飞书群等都支持webHook机器人，咱们是否有计划增加webHook的方式告警呢？

**Comment by aiwenmo** [comment]
Dinky 的报警模块学习的 Apache DolphinScheduler 先进的设计及扩展方式，理论上 DolphinScheduler 支持的报警方式都可以便捷地在 Dinky 中实现，如 飞书的 webHook 。欢迎小伙伴 PR ，最后再次感谢 DolphinScheduler 社区及团队的支持！

**Comment by zhu-mingye** [comment]
It's a good idea. I'm working on it
