### ISSUE TITLE
local模式下的流作业，没地方关闭，一直运行

### ISSUE THREAD

**Issue by txl2017** [DataLinkDC/dlink#219]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

如题

### What you expected to happen

希望跟远程提交的作业一样，可以管理监控起来

### How to reproduce

希望跟远程提交的作业一样，可以管理监控起来，或者提供一个关闭的地方，不然只能重启dlink？

### Version

0.6.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
目前版本请不要使用local模式运行流任务，在 0.7.0 版本中将构建多版本 FlinkClientServer，后续则可以管理监控 local 的所有内容

**Comment by txl2017** [comment]
> 目前版本请不要使用local模式运行流任务，在 0.7.0 版本中将构建多版本 FlinkClientServer，后续则可以管理监控 local 的所有内容

好的

**Comment by txl2017** [comment]
> 目前版本请不要使用local模式运行流任务，在 0.7.0 版本中将构建多版本 FlinkClientServer，后续则可以管理监控 local 的所有内容

所以，要重启dlink才能停止吧

**Comment by aiwenmo** [comment]
> > 目前版本请不要使用local模式运行流任务，在 0.7.0 版本中将构建多版本 FlinkClientServer，后续则可以管理监控 local 的所有内容
> 
> 所以，要重启dlink才能停止吧

重启dlink才能停止

**Comment by txl2017** [comment]
> > > 目前版本请不要使用local模式运行流任务，在 0.7.0 版本中将构建多版本 FlinkClientServer，后续则可以管理监控 local 的所有内容
> > 
> > 
> > 所以，要重启dlink才能停止吧
> 
> 重启dlink才能停止

好的，期待0.7早日推出，感谢
