### ISSUE TITLE
[Bug] [root] Modify the version in the root pom ,named mybatis-plus-boot-starter to latest

### ISSUE THREAD

**Issue by aiwenmo** [DataLinkDC/dlink#222]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

Modify the version in the root pom ,named mybatis-plus-boot-starter to latest

### What you expected to happen

There are loopholes.

### How to reproduce

There are loopholes.

### Version

0.6.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by taizilongxu** [comment]
Hi, assign me , thanks

**Comment by aiwenmo** [comment]
> Hi, assign me , thanks

Hi, you didn't test it. I have fixed it.
