### ISSUE TITLE
[Feature][docs]  add openAPI and integration documment  

### ISSUE THREAD

**Issue by walkhan** [DataLinkDC/dlink#226]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Write dinky OpenAPI documents and integration documents.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by feature09** [comment]
可以补充下返回内容具体信息么？稍微解释下。
