### ISSUE TITLE
是否计划支持在不重启服务的前提下支持flink多版本

### ISSUE THREAD

**Issue by hxp0618** [DataLinkDC/dlink#232]
我查看了官方文档，需要重启服务才能更换版本，是否计划支持在不重启服务的前提下支持flink多版本
![image](https://user-images.githubusercontent.com/30236140/159828382-2295d160-6859-45cd-a772-6f3c10fd876b.png)

_Originally posted by @hxp0618 in https://github.com/DataLinkDC/dlink/discussions/231_

**Comment by aiwenmo** [comment]
目前可以启动多个不同版本的dlink实例，0.7.0才会支持多server
