### ISSUE TITLE
[Bug] [user management] User password is incorrectly modified

### ISSUE THREAD

**Issue by PaperKite233** [DataLinkDC/dlink#233]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

When configuring a user, nothing has been modified on the page, and the password has changed

---

配置用户时，页面上没有修改任何内容，密码就发生了改变

### What you expected to happen

Password does not change

### How to reproduce

1. Create a new user. According to the document, the default password of ordinary users is 123456, and the password field of the user table is stored as e10adc3949ba59abbe56e057f20f883e
2. Switch to the ordinary user and log in successfully with the default password
3. Switch back to the admin user, configure the user without modifying anything, and click Finish. At this time, the password of the user table changes, and the value is 14e1b600b1fd579f47433b88e8d85291
4. Log out of the admin user and log in with the ordinary user again, the password is 123456, the login fails; use e10adc3949ba59abbe56e057f20f883e as the password, the login is successful

---

1. 新建一个用户，根据文档，普通用户默认密码为123456，user表password字段存储为e10adc3949ba59abbe56e057f20f883e
2. 切换到该普通用户，使用默认密码登录成功
3. 切换回admin用户，对该用户进行配置，没有修改任何内容，点击完成，此时user表password发生变化，值为14e1b600b1fd579f47433b88e8d85291
4. 退出admin用户，再次使用该普通用户登录，密码为123456，登录失败；使用e10adc3949ba59abbe56e057f20f883e作为密码，登录成功

### Version

0.6.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
This is a bug. The password is also updated when the user information is modified.

**Comment by PaperKite233** [comment]
There is another problem in this place. No nickname is configured when creating a new ordinary user. After logging in with this ordinary user, the user is always loading in the upper right corner of the page, and there is no button to log out. I have to clear the cookie to log out.

---

这个地方还有一个问题，新建普通用户时不配置昵称，当使用这个普通用户登录后，页面右上角用户一直在加载的状态，同时没有退出登录的按钮，我不得不清空Cookie退出

**Comment by PaperKite233** [comment]
> There is another problem in this place. No nickname is configured when creating a new ordinary user. After logging in with this ordinary user, the user is always loading in the upper right corner of the page, and there is no button to log out. I have to clear the cookie to log out.
> 
> 这个地方还有一个问题，新建普通用户时不配置昵称，当使用这个普通用户登录后，页面右上角用户一直在加载的状态，同时没有退出登录的按钮，我不得不清空Cookie退出

Ordinary users who configure nicknames do not have this problem

---

配置昵称的普通用户没有这个问题

**Comment by aiwenmo** [comment]
I will fix it soon. Thank u.

**Comment by PaperKite233** [comment]
thx.
