### ISSUE TITLE
[Bug] [运维中心] 运维中心中查询不到Jar类型的任务

### ISSUE THREAD

**Issue by ChangjunZhang** [DataLinkDC/dlink#234]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

运维中心中看不到jar类型的任务，第一张图为运维中心，第二张为运行历史
![image](https://user-images.githubusercontent.com/22833148/159907676-2d65d004-ee5f-4f53-98c1-f1221bda6398.png)
![image](https://user-images.githubusercontent.com/22833148/159907796-efba7d97-2e73-42e8-8199-023ae147b863.png)

### What you expected to happen

运维中心，管理查看各种类型的任务

### How to reproduce

提交jar->到运维中心查看

### Anything else

no

### Version

0.6.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
在排查中
