### ISSUE TITLE
[Bug] [dlink-admin] 血缘解析异常 

### ISSUE THREAD

**Issue by sandiegoe** [DataLinkDC/dlink#263]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

flink-sql中有两条insert into 语句，如下图所示，应该要生成两条血缘，实际只解析出一条血缘。
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/23546379/160313840-86a6645d-f74f-4802-a08e-9ea08de240cb.png">
另外，计算血缘多点几次之后，图就会重叠在一块儿，如下图所示
![Uploading 6FFBBDB1613C7D4AA2DD2D502C928DEC.jpg…]()

### What you expected to happen

解析出两条血缘，且显示正常

### How to reproduce

如截图所示，写两个insert into语句即可复现

### Version

0.6.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
I will fix to it. thx

**Comment by aiwenmo** [comment]
I will fix to it. thx

**Comment by aiwenmo** [comment]
I will fix it. thx
