### ISSUE TITLE
[Feature][client] Add Flink client 1.15

### ISSUE THREAD

**Issue by aiwenmo** [DataLinkDC/dlink#275]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add Flink client 1.15

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liuzhuang2017** [comment]
@aiwenmo , This issue is very good.Hope it can be realized soon, thanks.

**Comment by aiwenmo** [comment]
Welcome to test it.thx
