### ISSUE TITLE
[Feature]撒时候支持mongodb

### ISSUE THREAD

**Issue by ctracerpp** [DataLinkDC/dlink#292]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
数据源的话可以自行扩展，Flink的话用相关依赖即可
