### ISSUE TITLE
[Bug] [Module Name] Bug title  com.dlink.exception.MetaDataException: 不支持数据源类型【ClickHouse】，请在 lib 下添加扩展依赖

### ISSUE THREAD

**Issue by wang316902972** [DataLinkDC/dlink#313]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

 com.dlink.exception.MetaDataException: 不支持数据源类型【ClickHouse】，请在 lib 下添加扩展依赖

### What you expected to happen

已经在plugins 和lib目录添加了 clickhouse-jdbc-0.2.6.jar，还需要添加什么包？

### How to reproduce

数据源添加clickhouse

### Version

0.6.1-SNAPSHOT

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
你是IDEA调试呢还是打包运行呢

**Comment by wang316902972** [comment]
> 你是IDEA调试呢还是打包运行呢

打包运行的，java -jar dlink-admin-0.6.1-SNAPSHOT.jar

**Comment by zhu-mingye** [comment]
> > 你是IDEA调试呢还是打包运行呢
> 
> 打包运行的，java -jar dlink-admin-0.6.1-SNAPSHOT.jar

需要使用dlink下的auto.sh (start|stop|restart|status) 执行启动dlink    如需使用 java -jar  dlink-admin-0.6.1-SNAPSHOT.jar 后面需要加 -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false

**Comment by wang316902972** [comment]
> > > 你是IDEA调试呢还是打包运行呢
> > 
> > 
> > 打包运行的，java -jar dlink-admin-0.6.1-SNAPSHOT.jar
> 
> 需要使用dlink下的auto.sh (start|stop|restart|status) 执行启动dlink 如需使用 java -jar dlink-admin-0.6.1-SNAPSHOT.jar 后面需要加 -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false

用sh auto.sh start 执行命令后没有任何反应，报错信息哪里查看呢？

**Comment by zhu-mingye** [comment]
dlink 根目录下的dlink.log
dlink.log 用于记录当下的日志
dlink/log/  用于记录合并历史日志

**Comment by wang316902972** [comment]
> dlink 根目录下的dlink.log dlink.log 用于记录当下的日志 dlink/log/ 用于记录合并历史日志
1、采用这方式启动后，没有Log
[root@slave8 dlink]# sh auto.sh start
[root@slave8 dlink]# cd logs/
[root@slave8 logs]# ll
总用量 0
 2、采用[root@slave8 dlink]# java -jar dlink-admin-0.6.1-SNAPSHOT.jar  -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false 
方式启动后添加MySQL数据源，还是报错
[dlink] 2022-04-03 11:36:19.724 ERROR com.dlink.exception.WebExceptionHandler 43 unknownException - ERROR: com.dlink.exception.MetaDataException: 不支持数据源类型【MySql】，请在 lib 下添加扩展依赖

**Comment by wang316902972** [comment]
> dlink 根目录下的dlink.log dlink.log 用于记录当下的日志 dlink/log/ 用于记录合并历史日志
1、采用这方式启动后，没有Log
[root@slave8 dlink]# sh auto.sh start
[root@slave8 dlink]# cd logs/
[root@slave8 logs]# ll
总用量 0
 2、采用[root@slave8 dlink]# java -jar dlink-admin-0.6.1-SNAPSHOT.jar  -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false 
方式启动后添加MySQL数据源，还是报错
[dlink] 2022-04-03 11:36:19.724 ERROR com.dlink.exception.WebExceptionHandler 43 unknownException - ERROR: com.dlink.exception.MetaDataException: 不支持数据源类型【MySql】，请在 lib 下添加扩展依赖

**Comment by zhu-mingye** [comment]
> > dlink 根目录下的dlink.log dlink.log 用于记录当下的日志 dlink/log/ 用于记录合并历史日志
> > 1、采用这方式启动后，没有Log
> > [root@slave8 dlink]# sh auto.sh start
> > [root@slave8 dlink]# cd logs/
> > [root@slave8 logs]# ll
> > 总用量 0
> > 2、采用[root@slave8 dlink]# java -jar dlink-admin-0.6.1-SNAPSHOT.jar  -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false
> > 方式启动后添加MySQL数据源，还是报错
> > [dlink] 2022-04-03 11:36:19.724 ERROR com.dlink.exception.WebExceptionHandler 43 unknownException - ERROR: com.dlink.exception.MetaDataException: 不支持数据源类型【MySql】，请在 lib 下添加扩展依赖

添加 mysql-connector-java-8.0.22.jar 到 lib/ 或者plugins 下   还有确保你执行了初始化建表sql文件dlink.sql  确保 application.yaml 配置正确

**Comment by aiwenmo** [comment]
> > > > 你是IDEA调试呢还是打包运行呢
> > > 
> > > 
> > > 打包运行的，java -jar dlink-admin-0.6.1-SNAPSHOT.jar
> > 
> > 
> > 需要使用dlink下的auto.sh (start|stop|restart|status) 执行启动dlink 如需使用 java -jar dlink-admin-0.6.1-SNAPSHOT.jar 后面需要加 -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false
> 
> 用sh auto.sh start 执行命令后没有任何反应，报错信息哪里查看呢？

看看你得auto.sh 文件内容是不是变成了一行，如果是的话就手动从源码里拷贝一个新的吧

**Comment by aiwenmo** [comment]
> > dlink 根目录下的dlink.log dlink.log 用于记录当下的日志 dlink/log/ 用于记录合并历史日志
> > 1、采用这方式启动后，没有Log
> > [root@slave8 dlink]# sh auto.sh start
> > [root@slave8 dlink]# cd logs/
> > [root@slave8 logs]# ll
> > 总用量 0
> > 2、采用[root@slave8 dlink]# java -jar dlink-admin-0.6.1-SNAPSHOT.jar  -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false
> > 方式启动后添加MySQL数据源，还是报错
> > [dlink] 2022-04-03 11:36:19.724 ERROR com.dlink.exception.WebExceptionHandler 43 unknownException - ERROR: com.dlink.exception.MetaDataException: 不支持数据源类型【MySql】，请在 lib 下添加扩展依赖

-Dloader.path 等参数需要加到 -jar 前面才能生效

**Comment by wang316902972** [comment]
> > > > > 你是IDEA调试呢还是打包运行呢
> > > > 
> > > > 
> > > > 打包运行的，java -jar dlink-admin-0.6.1-SNAPSHOT.jar
> > > 
> > > 
> > > 需要使用dlink下的auto.sh (start|stop|restart|status) 执行启动dlink 如需使用 java -jar dlink-admin-0.6.1-SNAPSHOT.jar 后面需要加 -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false
> > 
> > 
> > 用sh auto.sh start 执行命令后没有任何反应，报错信息哪里查看呢？
> 
> 看看你得auto.sh 文件内容是不是变成了一行，如果是的话就手动从源码里拷贝一个新的吧

是这个问题，已解决！谢谢
另外密码设置太长了，是否能通过修改表结构长度来解决？
; Data truncation: Data too long for column 'password' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'password' at row 1

**Comment by aiwenmo** [comment]
> > > > > > 你是IDEA调试呢还是打包运行呢
> > > > > 
> > > > > 
> > > > > 打包运行的，java -jar dlink-admin-0.6.1-SNAPSHOT.jar
> > > > 
> > > > 
> > > > 需要使用dlink下的auto.sh (start|stop|restart|status) 执行启动dlink 如需使用 java -jar dlink-admin-0.6.1-SNAPSHOT.jar 后面需要加 -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false
> > > 
> > > 
> > > 用sh auto.sh start 执行命令后没有任何反应，报错信息哪里查看呢？
> > 
> > 
> > 看看你得auto.sh 文件内容是不是变成了一行，如果是的话就手动从源码里拷贝一个新的吧
> 
> 是这个问题，已解决！谢谢 另外密码设置太长了，是否能通过修改表结构长度来解决？ ; Data truncation: Data too long for column 'password' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'password' at row 1

根据自己的需求，只修改用户表的密码字段长度即可。

**Comment by wang316902972** [comment]
> > > > > > > 你是IDEA调试呢还是打包运行呢
> > > > > > 
> > > > > > 
> > > > > > 打包运行的，java -jar dlink-admin-0.6.1-SNAPSHOT.jar
> > > > > 
> > > > > 
> > > > > 需要使用dlink下的auto.sh (start|stop|restart|status) 执行启动dlink 如需使用 java -jar dlink-admin-0.6.1-SNAPSHOT.jar 后面需要加 -Dloader.path=./lib,./plugins -Ddruid.mysql.usePingMethod=false
> > > > 
> > > > 
> > > > 用sh auto.sh start 执行命令后没有任何反应，报错信息哪里查看呢？
> > > 
> > > 
> > > 看看你得auto.sh 文件内容是不是变成了一行，如果是的话就手动从源码里拷贝一个新的吧
> > 
> > 
> > 是这个问题，已解决！谢谢 另外密码设置太长了，是否能通过修改表结构长度来解决？ ; Data truncation: Data too long for column 'password' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'password' at row 1
> 
> 根据自己的需求，只修改用户表的密码字段长度即可。

OK！
-rwxrwxrwx. 1 root root   10046 3月  31 19:08 dlink-alert-dingtalk-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root   11139 3月  31 19:08 dlink-alert-wechat-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root   38486 3月  31 19:07 dlink-client-1.13-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root   14112 3月  31 19:08 dlink-connector-jdbc-1.13-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root    7792 3月  31 19:08 dlink-function-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root   22794 3月  31 19:08 dlink-metadata-clickhouse-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root    7902 3月  31 19:08 dlink-metadata-doris-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root   12504 3月  31 19:08 dlink-metadata-hive-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root    6839 3月  31 19:08 dlink-metadata-mysql-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root    7901 3月  31 19:08 dlink-metadata-oracle-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root   10724 3月  31 19:08 dlink-metadata-phoenix-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root    6830 3月  31 19:08 dlink-metadata-postgresql-0.6.1-SNAPSHOT.jar
-rwxrwxrwx. 1 root root    9864 3月  31 19:08 dlink-metadata-sqlserver-0.6.1-SNAPSHOT.jar
lib下已经包含驱动了吧？不需要单独再添加驱动包了吧？

**Comment by aiwenmo** [comment]
https://github.com/DataLinkDC/dlink/blob/dev/docs/zh-CN/quick_start/deploy.md
