### ISSUE TITLE
SpringBoot与hadoop相关依赖冲突问题

### ISSUE THREAD

**Issue by aiwenmo** [DataLinkDC/dlink#34]
dlink 是一个后台基于SpringBoot的react项目，其提交JobGraph到集群执行时，依赖Flink的源码，当涉及hadoop相关依赖时，会出现servlet等依赖的冲突，当程序内部报错时会产生额外的servlet相关报错。
（待解决，可签领）

**Comment by yutaoChina** [comment]
我也发现了，hadoop2.6 2.7都有

**Comment by aikuyun** [comment]
+1

**Comment by aiwenmo** [comment]
可先暂时删除hadoop相关依赖里的javax.servlet，后续 RPC 版本将去解决该问题
