### ISSUE TITLE
[Bug] [dlink-web] 修改flink集群完成后显示“新增成功”

### ISSUE THREAD

**Issue by Arnu-** [DataLinkDC/dlink#352]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

集群配置管理-修改已有配置-点击“完成”-显示“新增成功”
![image](https://user-images.githubusercontent.com/8543167/161926620-8d6b9de8-f355-40d8-805c-8b70506fbdba.png)

### What you expected to happen

点击“完成” 应该显示 “修改成功”

### How to reproduce

集群配置管理-修改已有配置-点击“完成”-显示“新增成功”

### Version

0.6.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
嗯好，这是一类偷懒的bug，很多地方都有这种情况，hhh，后面集中处理下
