### ISSUE TITLE
自定义execute语法，yarn application模式提交有问题

### ISSUE THREAD

**Issue by txl2017** [DataLinkDC/dlink#354]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

自定义类似cdcsource的execute语法，使用yarn application模式提交，没有返回提交结果，而且也没提交到flink集群，看日志感觉是在本地跑。继续测试发现可以提交到yarn session集群，同样也没有返回执行结果，运维中心也看不到任务。

### What you expected to happen

希望自定义的datastream任务可以跟普通的sql任务一样

### How to reproduce

希望自定义的datastream任务可以跟普通的sql任务一样

### Version

0.6.1-SNAPSHOT

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
你用的cdcsource呢还是说自己扩展了一个新的语法

**Comment by txl2017** [comment]
> 你用的cdcsource呢还是说自己扩展了一个新的语法

扩展的新语法，参照的cdcsource，使用的execute，yarn session上任务正常跑，dlink没有获取到任务信息

**Comment by aiwenmo** [comment]
检查扩展的部分是否只包含 StreamExecutionEnvironment 的配置

**Comment by txl2017** [comment]
> 检查扩展的部分是否只包含 StreamExecutionEnvironment 的配置
确实是扩展的地方提交了任务，去掉之后正常了，谢谢
