### ISSUE TITLE
[Optimization] datagen 的数据print之后，debug过程中还会提示找不到job id.而抛出异常

### ISSUE THREAD

**Issue by ranqiqiang** [DataLinkDC/dlink#392]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

flink sql 编辑界面，进行datagen 数据集测试，仅print 数据。
大概几十秒之后，任务finshed。
但是debug 过程中，发现还会有线程继续在通过job id 找数据结果？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
确实有这个问题，你计划怎么解决呢

**Comment by ranqiqiang** [comment]
我还没找到代码，我猜测原理是你有定时任务扫描这个job，是否获取数据的时候，能通过api 获取这个任务的的状态，如果完成 或者失败，就停止该线程之类的？

**Comment by aiwenmo** [comment]
你猜错了，你可以追踪下 Flink 源码，在 Flink 源码里

**Comment by ranqiqiang** [comment]
行吧，我测试下，本地测试 plugins  下面放flink 的各种lib 包，还是会找不到？

**Comment by aiwenmo** [comment]
> 行吧，我测试下，本地测试 plugins 下面放flink 的各种lib 包，还是会找不到？

和这个issue有什么关系呢
