### ISSUE TITLE
[Feature][pom] flink version management

### ISSUE THREAD

**Issue by soaped** [DataLinkDC/dlink#394]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

If you want to switch to the Flink version, you need to change multiple POM files, it is easy to miss, it is inconvenient to manage

### Use case

切换flink版本时，遗漏了，导致异常；
When switching the FLINK version, miss it, resulting in anomalous

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi, do you plan to deal with it?
