### ISSUE TITLE
[Bug] Official website has typos

### ISSUE THREAD

**Issue by xsaffable** [DataLinkDC/dlink#421]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/34018346/163750255-22946d3d-a883-4bc2-bbe9-22a73a2f79ea.png)

### What you expected to happen

I think it should be "沉浸式".

### How to reproduce

Enter the official website.
http://www.dlink.top/

### Version

0.6.3-SNAPSHOT

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Yes, welcome to PR dinky-site. thx
