### ISSUE TITLE
[FAQ]FlinkSQL语句分割符处理问题

### ISSUE THREAD

**Issue by wwek** [DataLinkDC/dlink#424]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

SQL parse failed. Encountered ";" at line 9, column 2.

升级到0.6.2 后原本正常的sql报错，检查后发现是表中没有这个配置项
在系统设置中 修改保存下 FlinkSQL语句分割符 后解决
dlink_sys_config
![image](https://user-images.githubusercontent.com/1239403/163911229-1d3fc302-3f88-4c3a-85fa-fbb277049481.png)
![image](https://user-images.githubusercontent.com/1239403/163911246-9c22ff5d-8cfb-47a3-a665-6a5dded450ef.png)
![image](https://user-images.githubusercontent.com/1239403/163911280-e2909e2f-da3d-4972-9f18-1455ef08fa47.png)
![image](https://user-images.githubusercontent.com/1239403/163911285-5cbc8040-dede-49a9-9db0-ff67604137f6.png)

![image](https://user-images.githubusercontent.com/1239403/163911300-d8589850-153c-417c-a88e-5ea86606e626.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LucaQY** [comment]
我刚刚发现的一个情况是，设置为;\r\n为分隔符后，windows和mac在开发界面写SQL时，对同样的语句mac会无法通过检查，因为windows是CR LF，mac默认是只有LF。

**Comment by aiwenmo** [comment]
> 我刚刚发现的一个情况是，设置为;\r\n为分隔符后，windows和mac在开发界面写SQL时，对同样的语句mac会无法通过检查，因为windows是CR LF，mac默认是只有LF。

mac 修改分隔符为 ;\n 试试

**Comment by zhouchitc** [comment]
> 我刚刚发现的一个情况是，设置为;\r\n为分隔符后，windows和mac在开发界面写SQL时，对同样的语句mac会无法通过检查，因为windows是CR LF，mac默认是只有LF。

同样是mac，我是按照上面的说法，在设置了的语句分隔符了重新输入一边分号;  ，解决问题

**Comment by LucaQY** [comment]
> > 我刚刚发现的一个情况是，设置为;\r\n为分隔符后，windows和mac在开发界面写SQL时，对同样的语句mac会无法通过检查，因为windows是CR LF，mac默认是只有LF。
> 
> 同样是mac，我是按照上面的说法，在设置里的语句分隔符里重新输入一边分号; ，解决问题

是了，但;\r\n的意图就没起作用。
我们想让windows和mac的同事同时使用就只能用;了

**Comment by aiwenmo** [comment]
> > > 我刚刚发现的一个情况是，设置为;\r\n为分隔符后，windows和mac在开发界面写SQL时，对同样的语句mac会无法通过检查，因为windows是CR LF，mac默认是只有LF。
> > 
> > 
> > 同样是mac，我是按照上面的说法，在设置里的语句分隔符里重新输入一边分号; ，解决问题
> 
> 是了，但;\r\n的意图就没起作用。 我们想让windows和mac的同事同时使用就只能用;了

防止影响参数里的;，你也可以配置未两个;，如‘;;’。分隔符是自定义的，按需配置即可。当然也可以提个pr实现正则表达式来同时分割这两种情况

**Comment by aiwenmo** [comment]
> > > 我刚刚发现的一个情况是，设置为;\r\n为分隔符后，windows和mac在开发界面写SQL时，对同样的语句mac会无法通过检查，因为windows是CR LF，mac默认是只有LF。
> > 
> > 
> > 同样是mac，我是按照上面的说法，在设置里的语句分隔符里重新输入一边分号; ，解决问题
> 
> 是了，但;\r\n的意图就没起作用。 我们想让windows和mac的同事同时使用就只能用;了

可用 ;\r\n|;\n
