### ISSUE TITLE
[Optimization][admin] Add a restore job from checkpoint

### ISSUE THREAD

**Issue by qq919856** [DataLinkDC/dlink#450]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

When the Flink task fails, if savePoint is not saved, there is no good way to restore the job. It is recommended to add checkpoint recovery or restore the job from the last checkpoint

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. Have you solved it?
