### ISSUE TITLE
[Bug] [Admin]  yarn-per-job mode task, the resources are not automatically released when the batch task ends

### ISSUE THREAD

**Issue by liulian6** [DataLinkDC/dlink#483]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

建立一个批任务采用yarn-pre-job方式，任务结束时，yarn中资源未被释放

### What you expected to happen

批任务结束，yarn中资源自动释放

### How to reproduce

建立一个批任务采用yarn-pre-job方式，任务结束时，查看yarn中任务，存在

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
This is a bug.

**Comment by zhengtingxue** [comment]
我还以为是专门留着，可以方便看jm的日志呢

**Comment by aiwenmo** [comment]
已修复
