### ISSUE TITLE
[Bug] [flinkSql] 当flinksql运行失败只剩下jobmanager平台不能处理失败残余

### ISSUE THREAD

**Issue by wmtbnbo** [DataLinkDC/dlink#487]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

当我在平台启动了一个flinksql，运行失败后，界面显示运行失败
![企业微信截图_16520650782194](https://user-images.githubusercontent.com/44955013/167333149-792db4f6-8d45-486a-8446-d59cb0bd4e88.png)
但是我在yarn上面还能够看到该程序的jobmanager仍然在运行
![企业微信截图_16520652118590](https://user-images.githubusercontent.com/44955013/167333285-338ccbb5-b1d6-4755-9766-2872e6397104.png)
我重启该任务后，yarn界面出现了两个任务

### What you expected to happen

我认为，当出现这种程序内部只剩下jobmanager时，应该自动杀死存在yarn的残留程序，或者在界面设计一个对这种情况继续杀停的按钮。

### How to reproduce

启动一个yarn per job测试flinksql通过内部逻辑让其运行失败即可复现

### Version

0.6.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
#483
