### ISSUE TITLE
[Bug] [web] Refresh the status page with abnormal jitter

### ISSUE THREAD

**Issue by wmtbnbo** [DataLinkDC/dlink#491]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

当我点击刷新，下面框内页面出现模块抖动
![企业微信截图_16521448124750](https://user-images.githubusercontent.com/44955013/167522457-34e12df8-6f0d-48ac-9d42-d83a2a1845f7.png)

### What you expected to happen

模块抖动是一个异常行为

### How to reproduce

刷新即可

### Version

0.6.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
嗯是不是更新时间的format不一样

**Comment by wmtbnbo** [comment]
> 嗯是不是更新时间的format不一样

是的，是否可以考虑时间格式直接在后端处理好？

**Comment by aiwenmo** [comment]
可以自己调试下改改看，这个在 IDEA 里就可调试

**Comment by wmtbnbo** [comment]
> 可以自己调试下改改看，这个在 IDEA 里就可调试

在实体类com.dlink.model.JobInstance的做如下添加前端传输格式规范即可

```
  ++  @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
         @TableField(fill = FieldFill.INSERT_UPDATE)
         private LocalDateTime updateTime;
```

**Comment by aiwenmo** [comment]
嗯好，感谢，可以提个pr

**Comment by wmtbnbo** [comment]
> 嗯好，感谢，可以提个pr

好的，我去提一个
