### ISSUE TITLE
[Bug] [data sync] Configuration information is out of sync

### ISSUE THREAD

**Issue by wmtbnbo** [DataLinkDC/dlink#493]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

先配置一个flinksql并且设置savepoint为最近一次，提交任务，然后在运维中心停止任务，随后在数据开发调整savepoint策略为制定某次点击保存。此时再去运维中心重启该任务，发现该任务还是按照最近一次的方式提交，刷新后依然还是最近一次的配置

### What you expected to happen

配置是否应该同步变动，自动将以前的配置转换为历史版本？

### How to reproduce

安装步骤执行即可

### Version

0.6.3-SNAPSHOT

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
看看savepoint策略的修改保存上了吗，目前作业配置保存这块有个bug，特殊条件下会导致前端没有传最新值到后台，在排查

**Comment by wmtbnbo** [comment]
> 看看savepoint策略的修改保存上了吗，目前作业配置保存这块有个bug，特殊条件下会导致前端没有传最新值到后台，在排查
保存显示是成功了，我去数据库看dlink_task表里的数据也是被更新了，但是在运维中心刷新并没有变化

**Comment by wmtbnbo** [comment]
> 看看savepoint策略的修改保存上了吗，目前作业配置保存这块有个bug，特殊条件下会导致前端没有传最新值到后台，在排查

保存显示是成功了，我去数据库看dlink_task表里的数据也是被更新了，但是在运维中心刷新并没有变化

**Comment by aiwenmo** [comment]
> > 看看savepoint策略的修改保存上了吗，目前作业配置保存这块有个bug，特殊条件下会导致前端没有传最新值到后台，在排查
> 
> 保存显示是成功了，我去数据库看dlink_task表里的数据也是被更新了，但是在运维中心刷新并没有变化，当我在数据开发这里重新提交，此时运维中心里面会被刷新

运维中心刷新并没有变化是指什么

**Comment by wmtbnbo** [comment]
> > > 看看savepoint策略的修改保存上了吗，目前作业配置保存这块有个bug，特殊条件下会导致前端没有传最新值到后台，在排查
> > 
> > 
> > 保存显示是成功了，我去数据库看dlink_task表里的数据也是被更新了，但是在运维中心刷新并没有变化，当我在数据开发这里重新提交，此时运维中心里面会被刷新
> 
> 运维中心刷新并没有变化是指什么

无论我是直接刷新页面，还是点击如下的刷新，这里显示都没有变化，当然提及我也都是还是按照最开始的配置提交
![image](https://user-images.githubusercontent.com/44955013/167787972-c1b77467-276a-4b7b-b84c-eb7dd7e2af31.png)

**Comment by aiwenmo** [comment]
嗯好，谢谢反馈，在排查中

**Comment by aiwenmo** [comment]
源码中重启任务强制savepoint策略为最近一次，详情见 TaskServiceImpl 的 restartTask 实现
