### ISSUE TITLE
[Bug] [dlink-phoneix-connector] 插入数据时报错“UpsertStreamTableSink requires that Table has a full primary keys if it is updated.” 

### ISSUE THREAD

**Issue by freewind1977** [DataLinkDC/dlink#496]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/26646785/167798316-defd6874-f679-42ab-a4f3-c8a1a45eb149.png)

### What you expected to happen

将测试的flink sql 的sink换成mysql是可以正常通过的。应该是phoenix sink的问题。常规的插入可以正常入库，但是对于分组后数据或是有子查询+分组的就有问题

### How to reproduce

-- 单元测试 flink sql 
CREATE TABLE message
(
    device_id     bigint,       
    battery_power int,          
    notify_type   varchar,      
    verify_code   varchar,      
    create_time   timestamp(3), 
    device_status varchar,         
    data_type     varchar          
)
WITH (
    'connector' = 'jdbc',
    'url' = 'xxxxx',
    'driver' = 'com.mysql.cj.jdbc.Driver',
    'username' = 'xxxxx',
    'password' = 'xxxxx',
    'table-name' = 'xxxxx'
);

CREATE TABLE PV100(
    `SID` bigint,
    `UCOUNT` bigint,
    primary key(`SID`) not enforced
)with(
	'connector.type'='phoenix',
    'connector.url'='jdbc:phoenix:xxxxx:2181',
    'connector.table'='PV100',
    'connector.driver'='org.apache.phoenix.jdbc.PhoenixDriver',
    'connector.username'='',
    'connector.password'='',
    'connector.write.flush.max-rows'='30',
    'phoenix.schema.isnamespacemappingenabled'='false',
    'phoenix.schema.mapsystemtablestonamespace'='false'
);

INSERT INTO PV100
SELECT device_id ,count(device_status) as num
FROM message
group by device_id,device_status;

### Version

0.6.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaogao110** [comment]
you should select a, count(b) from xx group by a  ~
