### ISSUE TITLE
[Bug] [Savepoint] 通过Savepoint重新启动失败

### ISSUE THREAD

**Issue by roy-long** [DataLinkDC/dlink#532]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/28853880/170230063-534d294e-0949-4116-9ad3-0deabaf7292e.png)

### What you expected to happen

怎么解决这个问题？

### How to reproduce

flink。。。。。。。。。

### Version

0.6.3-SNAPSHOT

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by roy-long** [comment]
文件在的
![image](https://user-images.githubusercontent.com/28853880/170391002-d490d22d-c0b1-4eb2-80c1-62263702b01f.png)

**Comment by aiwenmo** [comment]
FlinkSQL 或 算子是否有变动呢

**Comment by roy-long** [comment]
没有变动过

**Comment by aiwenmo** [comment]
用的哪个参数

**Comment by roy-long** [comment]
yarn-session

**Comment by aiwenmo** [comment]
是指怎么指定的参数来恢复作业的，使用的最近一次吗

**Comment by roy-long** [comment]
对的，策略是最近一次的 ，后面我找到hdfs上的savepoint路径，自定义恢复作业，也是一样的

**Comment by aiwenmo** [comment]
我刚刚测试，同一任务从 savepoint 和 checkpoint 恢复都没有问题，怀疑你的任务可能发生了变化

**Comment by roy-long** [comment]
不知道，是不是因为我用的是flink1.15版本的问题，flink.conf配置文件我是默认没有设置savepoint，checkpoint路径的，改了点代码，通过studio任务那里传进去的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月2日(星期四) 下午2:30
收件人: ***@***.***&gt;; 
抄送: "just ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DataLinkDC/dlink] [Bug] [Savepoint] 通过Savepoint重新启动失败 (Issue #532)





 
我刚刚测试，同一任务从 savepoint 和 checkpoint 恢复都没有问题，怀疑你的任务可能发生了变化

**Comment by aiwenmo** [comment]
我的flink是1.13.6。

**Comment by roy-long** [comment]
可以帮我远程看一下么，我感觉我也没改什么东西

**Comment by aiwenmo** [comment]
晚上可以，通过微信联系我

**Comment by roy-long** [comment]
好的，我过几天再找你帮忙把，今晚要开车回老家
