### ISSUE TITLE
[Bug] [web] 注册的数据源“别名”为空时，单击数据开发>元数据>选择数据源时只显示数据源类型，不显示名称

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dlink#541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

在注册中心配置数据源时没有添加“别名”，保存后，单击数据开发>元数据>选择数据源，会发现只显示数据源种类，而不会显示名称，让人分不清具体是哪个数据源。
![图片](https://user-images.githubusercontent.com/2136182/170685642-0a719899-870d-4dbe-8be5-98b3dd7b091d.png)

### What you expected to happen

在没有给数据源添加别名时，直接显示配置的数据源名称，而不是数据源类型。

### How to reproduce

在注册中心配置数据源时不写“别名”，保存后，单击数据开发>元数据>选择数据源，会发现只显示数据源种类，而不会显示名称，让人分不清具体是哪个数据源。

### Version

0.6.3-SNAPSHOT

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhu-mingye** [comment]
Thank you for your feedback , this bug has been fixed
