### ISSUE TITLE
[Optimization] [datastudio] Logo icon disappeared when clicking MySQL type job

### ISSUE THREAD

**Issue by leeoo** [DataLinkDC/dlink#575]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

Logo icon disappeared when clicking MySQL type job

### What you expected to happen

Logo icon can be display when clicking MySQL type job.

### How to reproduce

datastudio>directory>click one of the MySQL type job

![图片](https://user-images.githubusercontent.com/2136182/172089392-9fb856f9-6569-4e83-b1ec-d655a07f3242.png)

### Version

0.6.4

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhu-mingye** [comment]
选中的背景色把 Logo icon 挡住了 并没有消失

**Comment by leeoo** [comment]
是不是可以把选中的背景色改成其他颜色，让图标可见呢？

**Comment by zhu-mingye** [comment]
> 

不影响功能使用  后期优化
