### ISSUE TITLE
您好，作者，请问是否支持starrocks

### ISSUE THREAD

**Issue by jinyan2049** [DataLinkDC/dlink#58]
可以的话，也请帮忙支持一下！
因为大量的left join，这种报表，clickhouse并发太差不适合搞

另外是否有支付宝? 我想尽自己一份绵薄之力，支持一下这个项目！

**Comment by aiwenmo** [comment]
谢谢支持，可以加我vx单独沟通下 starrocks

**Comment by jinyan2049** [comment]
作者，您好，感谢你的回复，你的微信号是wenmo_ai 吗？我现在就加你
