### ISSUE TITLE
保存Flink作业时任务时，报错。

### ISSUE THREAD

**Issue by aikuyun** [DataLinkDC/dlink#59]
保存Flink作业时任务时，报错。
log报错信息如下：
### Cause: java.sql.SQLException: Field 'name' doesn't have a default value
; Field 'name' doesn't have a default value; nested exception is java.sql.SQLException: Field 'name' doesn't have a default value] with root cause java.sql.SQLException: Field 'name' doesn't have a default value

部分截图放在语雀上了：
https://www.yuque.com/docs/share/7075a314-bcb2-42a1-9d55-17e7ddfe59c0?#

**Comment by aiwenmo** [comment]
请问您当前使用的dlink的版本及部署包来源

**Comment by aikuyun** [comment]
> 请问您当前使用的dlink的版本及部署包来源

https://github.com/DataLinkDC/dlink/releases/tag/0.4.0 这个

**Comment by aiwenmo** [comment]
草稿不支持保存

**Comment by aikuyun** [comment]
> 草稿不支持保存

👌，谢谢
