### ISSUE TITLE
[Feature][function] 是否考虑支持自定义函数

### ISSUE THREAD

**Issue by gaopan-05** [DataLinkDC/dlink#591]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

支持用户上传自定义函数jar包，并在 flinksql 中使用

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wmtbnbo** [comment]
It supports function customization，The development method can refer to the flink official documents,Put the expansion package under directory `plugins/`.Use the following method to load functions in the SQL file：
`create function TO_CHAR AS 'com.haier.sql.udf.ToCharFunction';`

**Comment by Zzm0809** [comment]
#1153

**Comment by Zzm0809** [comment]
#1144

**Comment by Zzm0809** [comment]
#1137
