### ISSUE TITLE
[dlink][flinksql] 不支持add jar sql语句

### ISSUE THREAD

**Issue by xyls82** [DataLinkDC/dlink#594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

原生flink sql 支持 add jar sql 语句

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
dev已实现  等release0.7
