### ISSUE TITLE
[Bug] [dlink-core] 向地址格式为“<域名>:<端口>/<集群名>/”的Flink集群中提交SQL异常

### ISSUE THREAD

**Issue by DevHan2020** [DataLinkDC/dlink#602]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、目前使用的JobManger的地址格式为：“<域名>:<端口>/<集群名>/”，例如：flink.apache.org:8081/flink-test-1/
![image](https://user-images.githubusercontent.com/37903479/173530228-12be1a9d-90b4-47f6-ae38-7c43aa6b3675.png)
2、无法向此地址格式集群提交SQL，报错如下：
![image](https://user-images.githubusercontent.com/37903479/173531270-0eb4063e-58b2-44d6-9656-921d6a0cbf8a.png)

### What you expected to happen

希望可以正常向地址格式为“<域名>:<端口>/<集群名>/”的Flink集群中提交SQL，例如地址格式为：flink.apache.org:8081/flink-test-1/

### How to reproduce

1、添加地址格式为"<域名>:<端口>/<集群名>/"的Flink集群。
2、向此集群提交SQL。

### Anything else

Every time.

### Version

0.6.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
只支持 ip:port

**Comment by DevHan2020** [comment]
> 只支持ip:port

dlink只支持ip:port的形式，是因为Flink的ExecutionEnvironment.createRemoteEnvironment(host,port)方法不支持吗？
