### ISSUE TITLE
元数据字段 null 和 not null问题

### ISSUE THREAD

**Issue by xiaoguoguo777** [DataLinkDC/dlink#609]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

如果元数据字段是bigint类型，会被转出not null，但是库里实际上是default null。
![image](https://user-images.githubusercontent.com/107536083/173767239-2e0c16fb-5367-4535-9da2-fb617fdd1f52.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaopan-05** [comment]
![image](https://user-images.githubusercontent.com/72590193/174767053-41d7fccc-87bf-4edd-a4f8-baf51559e68d.png)
这儿写死了
