### ISSUE TITLE
[Optimization]  【运维中心】作业实例的作业快照信息、集群信息展示以及增加选择checkpoint进行启动的功能

### ISSUE THREAD

**Issue by mydq** [DataLinkDC/dlink#631]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

![image](https://user-images.githubusercontent.com/42607771/175193512-3bdd1765-acc9-4ea4-92ee-f91719b9b215.png)
![image](https://user-images.githubusercontent.com/42607771/175193538-7506b4ce-e96b-4443-b652-965dceb47b98.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhu-mingye** [comment]
有兴趣贡献吗   集群这块的后端代码在 dlink-core/src/main/java/com/dlink/api/FlinkAPI.java
