### ISSUE TITLE
Flink1.15版本使用checkpoint恢复失败

### ISSUE THREAD

**Issue by zhang534** [DataLinkDC/dlink#647]
### Search before asking

- [x] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

更新到Flink1.15版本后，使用checkpoint恢复出现失败

### What you expected to happen

![微信图片_20220627104404](https://user-images.githubusercontent.com/61574830/175850850-ab3452af-c20b-4a9e-b27f-a96b4491c2ae.png)
![微信图片_20220627104410](https://user-images.githubusercontent.com/61574830/175850866-3ca92526-f5b6-4e42-8a1a-e9ae08899cdd.png)

### How to reproduce

使用checkpoint恢复Flink任务

### Version

0.6.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wmtbnbo** [comment]
你先禁用checkpoint然后提交任务到集群，查看jobmanager的日志，看是否存在异常

**Comment by leeoo** [comment]
这个是 Flink 1.15 早期版本自身的 bug，在 Flink 1.15.2 版本中已经修复，升级到 Flink 1.15.2 应该能解决。

**Comment by aiwenmo** [comment]
> 这个是 Flink 1.15 早期版本自身的 bug，在 Flink 1.15.2 版本中已经修复，升级到 Flink 1.15.2 应该能解决。

嗯是的，可以试试看
