### ISSUE TITLE
[Optimization][数据开发]是否能够引入任务版本的概念

### ISSUE THREAD

**Issue by zhanghairui521** [DataLinkDC/dlink#662]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

在生产环境中，不可避免的会遇到任务回滚的情况，如果目录中引入能够版本管理的概念，用户可以更好的管理任务，并且当发生异常时能够快速回滚。最好能够根据版本号识别出当前运行版本的上一版本用于任务回滚。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
可以看下 #659
