### ISSUE TITLE
[Feature][数据开发、注册中心]是否能够提供任务及配置文件的复制新增功能

### ISSUE THREAD

**Issue by zhanghairui521** [DataLinkDC/dlink#663]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在作业开发的过程中，可能同一类型的任务要创建多个，如果有复制新增的功能将会带来很大的便利，配置文件也是如此。

### Use case

能够支持任务和配置文件的复制新增功能

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
这是一个好提议
