### ISSUE TITLE
[Bug] [Module Name] Bug title Cannot load user class: com.dlink.cdc.kafka.KafkaSinkBuilder 

### ISSUE THREAD

**Issue by zhaoysg** [DataLinkDC/dlink#672]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

在测试（实时数据同步至对应 kafka topic） 功能期间出现的问题 。 

### What you expected to happen

。

### How to reproduce

实时数据同步至对应 kafka topic

### Version

0.6.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhaoysg** [comment]
根据你现在的版本 找到以下相关的 dlink-client-1.13-0.6.2.jar， dlink-client-base-0.6.2.jar，dlink-common-0.6.2.jar  jar放到你的flink lib 下然后重启。你会发现问题解决

**Comment by zhaoysg** [comment]
根据你现在的版本 找到以下相关的 dlink-client-1.13-0.6.2.jar， dlink-client-base-0.6.2.jar，dlink-common-0.6.2.jar  jar放到你的flink lib 下然后重启。你会发现问题解决

**Comment by aiwenmo** [comment]
CDCSOURCE 需要把这三个依赖放到 Flink 集群lib下

**Comment by zhaoysg** [comment]
就是我遇到的这个问题  我分享出来， 防止其他同学在提问
