### ISSUE TITLE
[Feature][admin] 权限管理-数据源的维护页面增加权限管理

### ISSUE THREAD

**Issue by dzygcc** [DataLinkDC/dlink#694]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

目标： 防止平台的开发者通过平台获取数据源相关的密码。

通过权限管理，防止平台使用者通过数据源的相关页面和接口获取密码。
  1. 用户管理中引入权限管理，用户表扩展一个权限集合字段。
  2. 添加一个权限：数据源的增删改查权限，**默认所有用户拥有此权限**，只有超级管理员可以管理所有用户的该权限。
  3. 只有拥有数据源的增删改查权限的用户才能进入数据源相关的页面。

平台对涉及返回flinksql的接口进行脱敏处理，将password隐藏。
  1. 语法检查接口:  api/explainSql 
  2. 历史：flink语句：api/history
  4. 历史：异常信息：api/history

这样，开发者在编写job的时候通过变量引用的方式引用数据源，就可以避免数据库的密码被其他使用者看到。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
目前阶段可以认为 admin 用户具有管理的权限，其他无。接下来正在进行多租户及权限的合并，其中会涉及到角色的数据源权限。

**Comment by dzygcc** [comment]
> 

这个会做到什么程度呢，不相关的数据源密码，会被接口暴露出来吗，接口密码脱敏这个事应该没做吧？

**Comment by aiwenmo** [comment]
敏感信息可以使用全局变量，这样接口就不会暴露，比如数据源Flink链接配置全局变量

**Comment by dzygcc** [comment]
> 

我初步看了下，现在有几个接口都是直接暴露的，
语法检查接口: api/explainSql
历史：flink语句：api/history
历史：异常信息：api/history

返回里面有密码明文。

**Comment by dzygcc** [comment]
> 是的，目前所有接口都是暴露的，需要通过技巧避免，也可以添加您所说的 feature 来处理，期待您的贡献~

好的，那权限管理我先等社区其他贡献者的多租户开发结果，接口脱敏我先开始搞起来。

**Comment by dzygcc** [comment]
> 

1. 开发一个切面，通过正则匹配 password=abcd，将abcd 替换成*。
2. 对于有敏感信息泄露的接口打上注解。

**Comment by aiwenmo** [comment]
可以的，期待您的 PR

**Comment by dzygcc** [comment]
> 可以的，期待您的 PR

https://github.com/dzygcc/dlink/pull/1

**Comment by aiwenmo** [comment]
请提交至本仓库的 dev 分支，谢谢
