### ISSUE TITLE
[Bug] [admin] 1.6.5版本任务下线后，flink任务正常停止，dlink页面显示运行状态

### ISSUE THREAD

**Issue by qq919856** [DataLinkDC/dlink#698]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

背景:
1、flink1.13.5 Standalonemo
2、dlink1.6.5
3、版本从1.6.3升级到1.6.5
问题：
1、flinkSQL任务点击下线后，flink任务正常停止，dlink页面显示运行状态
2、且再次点击停止按钮，页面提示成功，但刷新后还是运行状态
![image](https://user-images.githubusercontent.com/46049797/177717802-fe295e5a-ceaa-4637-a847-e85629fc5026.png)

### What you expected to happen

任务应该下线后更新为停止状态，且任务手动停止成功

### How to reproduce

1、在dlink1.6.3中创建flinkSQL任务上线运行
2、将dlink版本更新到1.6.5
3、任务上线后，下线作业，
4、关掉当前作业页面，重新打开，会发现还是运行状态，但是已经下线

版本升级方式补充：
1、使用1.6.5的安装包
2、解压后，复制之前1.6.3的plugins包到1.6.5安装目录下
3、复制之前1.6.3的配置文件替换到1.6.5安装目录config包下
4、执行dlink 1.6.5的版本的sql文件：CREATE TABLE `dlink_task_version`
5、stop dlink 1.6.3 服务，启动1.6.5版本服务

### Version

0.6.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
请查看下表 dlink_job_instance 的记录

**Comment by aiwenmo** [comment]
哪个页面显示运行状态

**Comment by XiaoF-Liu** [comment]
![image](https://user-images.githubusercontent.com/46049797/183385747-96f83324-9d82-44e5-ba65-1f9fe422e5d9.png)
开发界面

**Comment by XiaoF-Liu** [comment]
本地环境没有复现该问题，测试环境升级后该问题复现不出来

**Comment by aiwenmo** [comment]
可以试试最新版本 0.6.6 可以复现该问题吗
