### ISSUE TITLE
[Bug] [运维中心] 在dinky正常运行，作业发布后，如果作业一直running，但是flink集群关闭情况下，运维中心重启后获取到作业状态一直running

### ISSUE THREAD

**Issue by qzgt** [DataLinkDC/dlink#700]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

在dinky正常运行，作业发布后，如果作业状态一直running，但是flink集群关闭情况下，运维中心重启后获取到作业状态一直running。

### What you expected to happen

希望运维中心的状态根据实时的进行，同时支持以dinky端数据为主，即如果dinky原来的作业状态为running状态，但是flink集群没有对应job或者已经关闭，那么dinky可以自动重启一个job。

### How to reproduce

直接在dinky-admin web端提交任务，然后直接关闭flink集群，然后重新启动dinky就可以复现。

### Version

0.6.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
请附截图

**Comment by JerryLen** [comment]
+1

**Comment by qzgt** [comment]
> 请附截图
截图如下：
![微信截图_20220711103914](https://user-images.githubusercontent.com/5117353/178178973-f4dbdde2-65fc-4ebc-9d26-e05749c61538.png)
![微信截图_20220711103936](https://user-images.githubusercontent.com/5117353/178178976-8588c231-94d1-442f-9083-442e35ca4dbe.png)

**Comment by qzgt** [comment]
> 请附截图

截图如下：

![微信截图_20220711103914](https://user-images.githubusercontent.com/5117353/178179059-22c989cb-206c-42d7-aec4-bc3f6b3a0a99.png)
![微信截图_20220711103936](https://user-images.githubusercontent.com/5117353/178179064-dd515a95-8115-4149-b66b-66c6f1391e93.png)

**Comment by aiwenmo** [comment]
这是正常的，因为由于意外原因无法请求到jobmanager，所以无法获取最新的算子状态，默认不更新，即还是RUNNING。

**Comment by aiwenmo** [comment]
任务实例状态已经更新为 UNKNOWN 了

**Comment by chen5306514** [comment]
我认为job instance的状态 和job history的状态应该保持一致才对，不然会出现状态不一致导致用户出现迷惑

**Comment by aiwenmo** [comment]
- [X] #1278
