### ISSUE TITLE
[Bug] application mode startup failed

### ISSUE THREAD

**Issue by waywtdcc** [DataLinkDC/dlink#701]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

 application mode startup failed

![image](https://user-images.githubusercontent.com/59957056/177927623-34a1097c-d9b3-4ce9-a4d4-173af08de2a6.png)
![image](https://user-images.githubusercontent.com/59957056/177927650-a056a0f0-0345-48fa-be84-81a9fa684405.png)

### What you expected to happen

 application mode startup 

### How to reproduce

 application mode startup 

### Version

0.6.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. Please debug the breakpoint at the exception.
