### ISSUE TITLE
Kubernetes Application Mode 页面为啥必须包含Hadoop 配置文件路径

### ISSUE THREAD

**Issue by xinggit** [DataLinkDC/dlink#71]
![image](https://user-images.githubusercontent.com/30068098/148174060-91a9a905-db19-4a15-9b86-8c4a476cdb02.png)

Kubernetes Application Mode 的集群配置，是否配置好 kubernetes 集群信息即可，其他信息写在模版 dockerfile 里，需自定义的配置在任务提交时设置

**Comment by xinggit** [comment]
我尝试在公司使用 dflink，我们现在所有 flink 程序都跑在 k8s 之上，通常情况下，我们只需要配置任务提交时的该 flink sql 作业特定的参数，其他内容都在 dockerfile 中写好，且在生产中，我们 flink 程序无需 hadoop 环境，同样 「lib 路径」 和 「配置文件路径」也无需，请问下 dflink 当前这样设计考虑的原因是什么呢？同时，这里我也很疑惑 kubernetes 的配置在哪设置呢？

**Comment by aiwenmo** [comment]
您好，目前，k8s的配置直接加在 flinksql 的 set 语法里，当前还没来得及改集群配置这块，k8s不需要配置集群配置。k8s application 目前需要提前部署好 dockerfile，具体内容请先联系我交流，谢谢

**Comment by xinggit** [comment]
期待
