### ISSUE TITLE
[Bug] [数据开发-执行当前SQL] NoSuchMethodError: org.apache.flink.table.catalog.FunctionCatalog

### ISSUE THREAD

**Issue by huanzui** [DataLinkDC/dlink#720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

Flink1.15.0

![image](https://user-images.githubusercontent.com/7300261/179337600-351a4f57-522e-494c-99cf-495bb9451052.png)

Caused by: java.lang.NoSuchMethodError: org.apache.flink.table.catalog.FunctionCatalog.<init>(Lorg/apache/flink/table/api/TableConfig;Lorg/apache/flink/table/catalog/CatalogManager;Lorg/apache/flink/table/module/ModuleManager;)V
	at com.dlink.executor.CustomTableEnvironmentImpl.create(CustomTableEnvironmentImpl.java:135) ~[dlink-client-1.13-0.6.5.jar:?]

添加了plugins

![image](https://user-images.githubusercontent.com/7300261/179337572-1f177bbc-213c-423f-af90-8cb433b35c95.png)

### What you expected to happen

正常运行

### How to reproduce

写好flinksql执行

### Version

0.6.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
切换 dlink-client.jar 为 1.15

**Comment by huanzui** [comment]
> 切换 dlink-client.jar 为 1.15

是需要自己切换1.15后编译是吧

**Comment by zhu-mingye** [comment]
> > 切换 dlink-client.jar 为 1.15
> 
> 是需要自己切换1.15后编译是吧

extends 下有
