### ISSUE TITLE
[Bug] k8s application模式，异步提交后报错

### ISSUE THREAD

**Issue by iamhungry** [DataLinkDC/dlink#732]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

k8s application模式，异步提交，Jobmanager和Taskmanager容器能正常启动；
但启动时flink的webui显示容器端口8081，此端口是dlink异常回调地址。访问不通。

### What you expected to happen

异常提交后，dlink能正常回调flink webui,获取jobid.

### How to reproduce

在k8s application 环境下，异步提交任务。

### Version

0.6.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Olave** [comment]
你好，可以看看你的dlink plugins 有哪些jar 吗？谢谢
k8s application 模式提交遇到：SQL parse failed. Non-query expression encountered in illegal context
![image](https://user-images.githubusercontent.com/23080394/179441630-2d539aed-41f6-4966-b8ca-48edb7be2fa6.png)

![image](https://user-images.githubusercontent.com/23080394/179441769-a86c0820-499a-4e61-bdea-c3e1fb4298d3.png)

**Comment by iamhungry** [comment]
<img width="598" alt="1658117367" src="https://user-images.githubusercontent.com/3936721/179444368-cb8b44bb-d52c-4ffc-b6cf-a36eb57d6c42.png">

**Comment by iamhungry** [comment]
@Olave 你提交后，看看有没有出现我遇到的问题。

**Comment by aiwenmo** [comment]
> 你好，可以看看你的dlink plugins 有哪些jar 吗？谢谢 k8s application 模式提交遇到：SQL parse failed. Non-query expression encountered in illegal context ![image](https://user-images.githubusercontent.com/23080394/179441630-2d539aed-41f6-4966-b8ca-48edb7be2fa6.png)
> 
> ![image](https://user-images.githubusercontent.com/23080394/179441769-a86c0820-499a-4e61-bdea-c3e1fb4298d3.png)

可以看看你提交的flinksql内容，是否包含完整的insert

**Comment by Olave** [comment]
> > 你好，可以看看你的dlink plugins 有哪些jar 吗？谢谢 k8s application 模式提交遇到：SQL parse failed. Non-query expression encountered in illegal context ![image](https://user-images.githubusercontent.com/23080394/179441630-2d539aed-41f6-4966-b8ca-48edb7be2fa6.png)
> > ![image](https://user-images.githubusercontent.com/23080394/179441769-a86c0820-499a-4e61-bdea-c3e1fb4298d3.png)
> 
> 可以看看你提交的flinksql内容，是否包含完整的insert

感谢回复，以下是我的sql语句：语法检查是通过的..
CREATE TABLE mysql_binlog (
 id INT NOT NULL,
 name STRING,
 PRIMARY KEY (id) NOT ENFORCED
) WITH (
 'connector' = 'mysql-cdc',
 'hostname' = '172.16.34.128',
 'port' = '32307',
 'username' = 'root',
 'password' = '123456',
 'database-name' = 'test',
 'table-name' = 'student'
);

CREATE TABLE test_kafka (
  -- schema is totally the same to the MySQL "products" table
  id INT,
  name STRING
) WITH (
 'connector' = 'kafka',
 'topic' = 'student',
 'properties.bootstrap.servers' = 'kafka-headless:9092',
 'properties.group.id' = 'testGroup',
 'properties.key.deserializer' = 'org.apache.kafka.common.serialization.StringDeserializer',
 'properties.value.deserializer' = 'org.apache.kafka.common.serialization.StringDeserializer',
 -- using 'debezium-json' as the format to interpret Debezium JSON messages
 -- please use 'debezium-avro-confluent' if Debezium encodes messages in Avro format
 'format' = 'debezium-json'
);

insert into test_kafka 
select id, name from mysql_binlog;
