### ISSUE TITLE
[Bug] yarn application模式下任务状态获取错误

### ISSUE THREAD

**Issue by waywtdcc** [DataLinkDC/dlink#744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

 yarn application模式下任务状态获取错误，任务已经完成，显示为unkown
![7d4d41837381437aa5baccd26a3ffe2](https://user-images.githubusercontent.com/59957056/179913435-d7a90648-d1d6-4a1b-9638-9cbf887489cf.png)
![c42310ac48dce401ab5f46041fac008](https://user-images.githubusercontent.com/59957056/179913444-fd62e335-62bf-47be-b661-cc4ba05a3ff0.png)

### What you expected to happen

 yarn application模式下任务状态获取yarn的任务状态

### How to reproduce

 yarn application模式下任务状态获取yarn的任务状态

### Version

0.6.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
目前来说，是正常的。如果你想把他改成 Finished，就需要去获取 yarn 的 application 状态了，欢迎贡献

**Comment by aiwenmo** [comment]
- [X] #1278
