### ISSUE TITLE
重装后还是加载了旧数据

### ISSUE THREAD

**Issue by yxiaoy6** [DataLinkDC/dlink#758]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

开始安装了0.6.5版本，之后重新拉取了0.6.1的包进行重装，数据库已经重新创建，但服务起来后还是显示0.6.5，且有些页面无法加载。
当前情况：
![image](https://user-images.githubusercontent.com/43592152/180381168-ca32b7c0-888a-45e3-a420-cb907b711023.png)
![image](https://user-images.githubusercontent.com/43592152/180381224-3b8dda0c-e5ae-4d4a-9c88-c7a94a9cb843.png)
![image](https://user-images.githubusercontent.com/43592152/180381273-64d9bfac-5ad0-49b0-90cb-8358dbf94ebc.png)

### What you expected to happen

怎么才能让0.6.1正常运行？

### How to reproduce

先运行一次0.6.5，再运行0.6.1

### Version

0.6.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
为什么要重装0.6.1呢

**Comment by yxiaoy6** [comment]
> 为什么要重装0.6.1呢

因为我装完0.6.5后，登录有点问题，刚登录进去刷新一下又需要重新登录，反复几次偶尔又能正常。所以我想安装个稳定版本的试试看

**Comment by aiwenmo** [comment]
> > 为什么要重装0.6.1呢
> 
> 因为我装完0.6.5后，登录有点问题，刚登录进去刷新一下又需要重新登录，反复几次偶尔又能正常。所以我想安装个稳定版本的试试看

重新登录是你被其他人顶了，分配一下账号就可了

**Comment by yxiaoy6** [comment]
> 



> > > 为什么要重装0.6.1呢
> > 
> > 
> > 因为我装完0.6.5后，登录有点问题，刚登录进去刷新一下又需要重新登录，反复几次偶尔又能正常。所以我想安装个稳定版本的试试看
> 
> 重新登录是你被其他人顶了，分配一下账号就可了

这样啊，了解了。dlink可以接入ldap吗？

**Comment by aiwenmo** [comment]
> > 
> 
> > > > 为什么要重装0.6.1呢
> > > 
> > > 
> > > 因为我装完0.6.5后，登录有点问题，刚登录进去刷新一下又需要重新登录，反复几次偶尔又能正常。所以我想安装个稳定版本的试试看
> > 
> > 
> > 重新登录是你被其他人顶了，分配一下账号就可了
> 
> 这样啊，了解了。dlink可以接入ldap吗？

需要自己扩展，欢迎贡献
