### ISSUE TITLE
[Bug] 注册 Flink Yarn Session 集群成功，但 Flink SQL 作业无法配置集群

### ISSUE THREAD

**Issue by wuuu0** [DataLinkDC/dlink#779]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

**问题描述：**
Dlink 成功启动日志无报错；成功注册了 Flink Yarn Session 集群，集群状态显示正常且可以返回心跳，对应日志无 error，但是有以下 warning：

`[dlink] 2022-07-26 17:21:29 CST WARN  org.springframework.core.log.CompositeLog 127 warn - Failed to evaluate Jackson deserialization for type [[simple type, class com.dlink.model.Cluster]]: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.fasterxml.jackson.datatype.jsr310.deser.LocalDateTimeDeserializer': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@2b71fc7e]`

![注册 Yarn Session Flink 集群.png](https://s2.loli.net/2022/07/26/wct8lMBnUSm6urJ.png)

然后新建 Flink SQL 作业，log 没有新增信息（无 info、warning、error），但是无法选择已注册的集群：
![Flink SQL 作业无法配置集群.png](https://s2.loli.net/2022/07/26/yUb2GoNMRYdWuKf.png)

### What you expected to happen

按照 [Yarn-Session 实践](http://www.dlink.top/docs/extend/practice_guide/yarnsubmit#yarn-session-%E5%AE%9E%E8%B7%B5)，实现在 Dlink 中提交 Flink SQL 作业到 Yarn Session 集群，并查看执行结果

### How to reproduce

**我的环境：**
Hadoop：3.0.0-cdh.6.3.4
Flink：1.15.0
Dlink：0.6.6

**我的 Plugins and FLINK_HOME/lib：**
![Plugins.png](https://s2.loli.net/2022/07/26/V4evIycGfAb6smn.png)

PS: 已经将 dlink-client 和 dlink-catalog-mysql 更换成了 extents 下的 1.15 版本，但 dlink-connector-jdbc 仍是 1.13 版本（未提供 1.15 版本）

**执行步骤：**
启动 Yarn Session；启动 Dlink；Dlink 注册 Yarn Session 集群；Dlink 创建 Flink SQL 作业，配置作业时发现无可选 Yarn Session 集群

### Version

0.6.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
请设置集群实例的类型为 Yarn Session

**Comment by wuuu0** [comment]
> 请设置集群实例的类型为 Yarn Session

跑通了，非常感谢
