### ISSUE TITLE
user changes their own password

### ISSUE THREAD

**Issue by yxiaoy6** [DataLinkDC/dlink#787]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

users can change their own passwords

### Related issues

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. At present, user password is managed by administrator.
Welcome to contribute code to realize users' own password management.

**Comment by duhanmin** [comment]
@aiwenmo I am willing to submit a PR!

**Comment by czy868** [comment]
我愿意来完成这个问题 @aiwenmo
