### ISSUE TITLE
[Feature][dlink-executor] 整库同步时，SINK端自动建库建表

### ISSUE THREAD

**Issue by iamhungry** [DataLinkDC/dlink#814]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

整库同步时，需要在启动同步任务前，手工建好sink端库和表。目标：sink端只要连接正常，在启动任务时，自动判断目标库或表是否存在，若不存在则自动创建。

### Use case

1、sink库不存在，启动任务时，库名自动创建
2、sink表不存在，启动任务时，表名自动创建
3、sink库或表存在时，任意重启任务，不影响数据

### Related issues

0.6.7

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dufeng1010** [comment]
I want to contribute auto create table for starrocks database. can you help me ? @aiwenmo @iamhungry
