### ISSUE TITLE
血缘功能模块，从@ant-design/charts引入的IndentedTreeGraph组件是没有的，导致报错了。请问作者原本想引入的是哪个组件呢？我这边想把血缘功能用上

### ISSUE THREAD

**Issue by huanganfree** [DataLinkDC/dlink#82]
![image](https://user-images.githubusercontent.com/41275935/148919432-b80e6816-88cf-42cb-a704-f5ef426ea82e.png)

**Comment by huanganfree** [comment]
![image](https://user-images.githubusercontent.com/41275935/148921229-c3f5d99f-a600-4ae2-a654-7c59e77a1d8b.png)
我看了下，目前@ant-design/charts里暴露出5个组件，好像都不行哎

**Comment by aiwenmo** [comment]
嗯前端依赖问题我先暂时调整下，后续计划用 Butterfly 实现

**Comment by huanganfree** [comment]
> 嗯前端依赖问题我先暂时调整下，后续计划用 Butterfly 实现

请问下，你的暂时调整方案是什么呢？回退@ant-design/charts库的版本吗？

**Comment by huanganfree** [comment]
> #83 看下这个

OK，谢谢
