### ISSUE TITLE
可以提前考虑多租户，命令空间的概念

### ISSUE THREAD

**Issue by wgzhxy** [DataLinkDC/dlink#86]
可以提前考虑多租户，命令空间的概念，划分不同的集群资源，不同的项目

**Comment by aiwenmo** [comment]
非常感谢您的建议，您所说的功能对于企业大规模应用至关重要，目前也正朝向这个方向建设，还希望接下来在构建多租户、命名空间、资源隔离等可以得到您的悉心指导，再次表示感谢。

**Comment by zhu-mingye** [comment]
#776
